In [87]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

## Extracting features of 2018 movies from Wikipedia

In [88]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [89]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [90]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],NaN
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN
...,...,...,...,...,...,...,...
267,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164]
268,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137]
269,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[228]
270,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[260]
271,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[261]

In [91]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\acer\anaconda3\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from tmdbv3api) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.10)

In [92]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '76d9e7057c5b2a49d4234f80154f044e'

In [93]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/550?api_key=76d9e7057c5b2a49d4234f80154f044e'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [94]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [95]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN,Drama
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN,Drama
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4],NaN,Drama
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN,Drama
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN,Drama
...,...,...,...,...,...,...,...,...
267,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164],Drama
268,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137],Drama
269,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[228],Drama
270,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[260],Drama
271,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[261],Drama

In [96]:
df_2018 = df[['Title','Cast and crew','genres']]

In [97]:
df_2018

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Drama
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Drama
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Drama
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Drama
...,...,...,...
267,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Drama
268,Vice,Adam McKay (director/screenplay); Christian Ba...,Drama
269,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama
270,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Drama
271,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Drama

In [98]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [99]:
df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

<ipython-input-99-4838efec492a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

In [100]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [101]:
df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

<ipython-input-101-94b1a1569c5d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

In [102]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [103]:
df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

<ipython-input-103-75f2be6b779a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

In [104]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [105]:
df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-105-c6969dc4d5e1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

In [106]:
df_2018

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Drama,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Drama,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Drama,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...,...
267,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Drama,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
268,Vice,Adam McKay (director/screenplay); Christian Ba...,Drama,Adam McKay,Christian Bale,Amy Adams,Steve Carell
269,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
270,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Drama,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
271,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Drama,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [107]:

df_2018 = df_2018.rename(columns={'Title':'movie_title'})

In [108]:
new_df18 = df_2018.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [109]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Drama,Insidious: The Last Key
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama,The Strange Ones
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Drama,Stratton
3,Warwick Thornton,Bryan Brown,Sam Neill,NaN,Drama,Sweet Country
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Drama,The Commuter
...,...,...,...,...,...,...
267,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Drama,Holmes & Watson
268,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Drama,Vice
269,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama,On the Basis of Sex
270,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Drama,Destroyer
271,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Drama,Black Mirror: Bandersnatch

In [110]:
new_df18['actor_2_name'] = new_df18['actor_2_name'].replace(np.nan, 'unknown')
new_df18['actor_3_name'] = new_df18['actor_3_name'].replace(np.nan, 'unknown')

In [111]:
new_df18['movie_title'] = new_df18['movie_title'].str.lower()

In [112]:
new_df18['comb'] = new_df18['actor_1_name'] + ' ' + new_df18['actor_2_name'] + ' '+ new_df18['actor_3_name'] + ' '+ new_df18['director_name'] +' ' + new_df18['genres']

In [113]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Drama,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Drama,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Drama,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
267,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Drama,holmes & watson,Will Ferrell John C. Reilly Rebecca Hall Etan ...
268,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Drama,vice,Christian Bale Amy Adams Steve Carell Adam McK...
269,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
270,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Drama,destroyer,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
271,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Drama,black mirror: bandersnatch,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

# Extracting features of 2019 movies from Wikipedia

In [115]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[3]
df2 = pd.read_html(link, header=0)[4]
df3 = pd.read_html(link, header=0)[5]
df4 = pd.read_html(link, header=0)[6]

In [116]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [117]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,Unnamed: 0,"Wikimedia Commons has media related to Films of the United States, 2019."
0,APRIL,5.0,Shazam!,Warner Bros. Pictures / New Line Cinema / DC F...,David F. Sandberg (director); Henry Gayden (sc...,[51],NaN,NaN
1,APRIL,5.0,Pet Sematary,Paramount Pictures,"Kevin Kolsch, Dennis Widmyer (directors); Jeff...",[52],NaN,NaN
2,APRIL,5.0,The Best of Enemies,STX Entertainment,Robin Bissell (director/screenplay); Taraji P....,[53],NaN,NaN
3,APRIL,5.0,High Life,A24 / Arte / ZDF / Canal+ / CinÃ©+,Claire Denis (director/screenplay); Jean-Pol F...,[54],NaN,NaN
4,APRIL,5.0,Unicorn Store,Netflix,Brie Larson (director); Samantha McIntyre (scr...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
188,DECEMBER,25.0,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132],NaN,NaN
189,DECEMBER,25.0,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[221],NaN,NaN
190,DECEMBER,25.0,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[222],NaN,NaN
191,DECEMBER,25.0,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[223],NaN,NaN
192,DECEMBER,27.0,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[224],NaN,NaN

In [118]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [119]:
df_2019 = df[['Title','Cast and crew','genres']]

In [120]:
df_2019

,Title,Cast and crew,genres
0,Shazam!,David F. Sandberg (director); Henry Gayden (sc...,Drama
1,Pet Sematary,"Kevin Kolsch, Dennis Widmyer (directors); Jeff...",Drama
2,The Best of Enemies,Robin Bissell (director/screenplay); Taraji P....,Drama
3,High Life,Claire Denis (director/screenplay); Jean-Pol F...,Drama
4,Unicorn Store,Brie Larson (director); Samantha McIntyre (scr...,Drama
...,...,...,...
188,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Drama
189,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama
190,1917,Sam Mendes (director/screenplay); Krysty Wilso...,Drama
191,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama
192,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [121]:
df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

<ipython-input-121-a433a4faa834>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

In [122]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

<ipython-input-122-eee71c5586b8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

In [123]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

<ipython-input-123-48d0aadc78c0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

In [124]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

<ipython-input-124-54baf96f0c44>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

In [125]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [126]:
new_df19 = df_2019.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [127]:

new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')

In [128]:
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [129]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [130]:
new_df19

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,David F. Sandberg,Zachary Levi,Asher Angel,Mark Strong,Drama,shazam!,Zachary Levi Asher Angel Mark Strong David F. ...
1,"Kevin Kolsch, Dennis Widmyer",Jason Clarke,Amy Seimetz,John Lithgow,Drama,pet sematary,Jason Clarke Amy Seimetz John Lithgow Kevin Ko...
2,Robin Bissell,Taraji P. Henson,Sam Rockwell,unknown,Drama,the best of enemies,Taraji P. Henson Sam Rockwell unknown Robin Bi...
3,Claire Denis,Robert Pattinson,Juliette Binoche,AndrÃ© Benjamin,Drama,high life,Robert Pattinson Juliette Binoche AndrÃ© Benjam...
4,Brie Larson,Brie Larson,Samuel L. Jackson,Joan Cusack,Drama,unicorn store,Brie Larson Samuel L. Jackson Joan Cusack Brie...
...,...,...,...,...,...,...,...
188,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Drama,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
189,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
190,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,Drama,1917,George MacKay Dean-Charles Chapman Mark Strong...
191,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
192,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

# Extracting features of 2020 movies from Wikipedia

In [1]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [3]:
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [4]:
tables = soup.find_all('table',class_='wikitable sortable')

In [5]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

In [6]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [7]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,JANUARY,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2],NaN
1,JANUARY,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3],NaN
2,JANUARY,10,Like a Boss,Paramount Pictures,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4],NaN
3,JANUARY,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN,NaN
4,JANUARY,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5],NaN
...,...,...,...,...,...,...,...
270,DECEMBER,25,We Can Be Heroes,Netflix / Troublemaker Studios,Robert Rodriguez (director/screenplay); Priyan...,NaN,[241]
271,DECEMBER,25,News of the World,Universal Pictures / Perfect World Pictures,Paul Greengrass (director/screenplay); Luke Da...,NaN,[242]
272,DECEMBER,25,One Night in Miami...,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,NaN,[243]
273,DECEMBER,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,NaN,[244]
274,DECEMBER,30,Pieces of a Woman,Netflix / Bron Studios,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,NaN,[245]

In [8]:
df_2020 = df[['Title','Cast and crew']]

In [9]:
df_2020

                     Title                                      Cast and crew
0               The Grudge  Nicolas Pesce (director/screenplay); Andrea Ri...
1               Underwater  William Eubank (director); Brian Duffield, Ada...
2              Like a Boss  Miguel Arteta (director); Sam Pitman, Adam Col...
3            Three Christs  Jon Avnet (director/screenplay); Eric Nazarian...
4        Inherit the Viper  Anthony Jerjen (director); Andrew Crabtree (sc...
..                     ...                                                ...
270       We Can Be Heroes  Robert Rodriguez (director/screenplay); Priyan...
271      News of the World  Paul Greengrass (director/screenplay); Luke Da...
272  One Night in Miami...  Regina King (director); Kemp Powers (screenpla...
273  Promising Young Woman  Emerald Fennell (director/screenplay); Carey M...
274      Pieces of a Woman  KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...

[275 rows x 2 columns]

In [10]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\acer\anaconda3\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from tmdbv3api) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (4.0.0)

In [11]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '76d9e7057c5b2a49d4234f80154f044e'

In [12]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if len(result) ==0:
        return np.NaN
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/550?api_key=76d9e7057c5b2a49d4234f80154f044e'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " "
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [13]:
df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre(str(x)))

<ipython-input-13-fdc91464740e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre(str(x)))

In [14]:
df_2020

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Drama
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Drama
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Drama
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama
...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Drama
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Drama
274,Pieces of a Woman,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,Drama

In [15]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [16]:
df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

<ipython-input-16-bc52fe9b0c35>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

In [17]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [18]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

<ipython-input-18-42c5f763f942>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [19]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [20]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

<ipython-input-20-ca9c918a7840>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [21]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [22]:

df_2020['actor_3_name'] = df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [23]:
df_2020

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Drama,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Drama,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Drama,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs
...,...,...,...,...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Drama,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama,Paul Greengrass,Tom Hanks,Helena Zengel,NaN
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Drama,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie
274,Pieces of a Woman,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,Drama,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker

In [24]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [25]:
new_df20 = df_2020.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [26]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Drama,The Grudge
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Drama,Underwater
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Drama,Like a Boss
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama,Inherit the Viper
...,...,...,...,...,...,...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Drama,We Can Be Heroes
271,Paul Greengrass,Tom Hanks,Helena Zengel,NaN,Drama,News of the World
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Drama,Promising Young Woman
274,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,Pieces of a Woman

In [27]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [28]:
new_df20 = new_df20.dropna(how='any')

In [29]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

<ipython-input-29-83e83e91073b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df20['movie_title'] = new_df20['movie_title'].str.lower()

In [30]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Drama,the grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Drama,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Drama,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,three christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
269,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Drama,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Drama,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
274,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker KornÃ©l...

# Extracting features of 2021 movies from wikipedia

In [32]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [33]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [34]:
! pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\acer\anaconda3\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from tmdbv3api) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (4.0.0)

In [35]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '76d9e7057c5b2a49d4234f80154f044e'

In [36]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,JANUARY,1.0,Shadow in the Cloud,Vertical Entertainment,Roseanne Liang (director/screenplay); Max Land...,[2],NaN
1,JANUARY,13.0,The White Tiger,Netflix,Ramin Bahrani (director/screenplay); Adarsh Go...,NaN,NaN
2,JANUARY,14.0,Locked Down,HBO Max / Warner Bros. Pictures,Doug Liman (director); Steven Knight (screenpl...,[3],NaN
3,JANUARY,15.0,The Dig,Netflix / Clerkenwell Films,Simon Stone (director); Moira Buffini (screenp...,[4],NaN
4,JANUARY,15.0,Outside the Wire,Netflix,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",[5],NaN
...,...,...,...,...,...,...,...
353,DECEMBER,25.0,The Tragedy of Macbeth,Apple TV+ / A24 / IAC Films,Joel Coen (director/screenplay); Denzel Washin...,NaN,[271]
354,DECEMBER,25.0,A Journal for Jordan,Columbia Pictures / Escape Artists / Bron Studios,Denzel Washington (director); Virgil Williams ...,NaN,[272]
355,DECEMBER,25.0,American Underdog,Lionsgate,"Erwin brothers (directors); Jon Erwin, David A...",NaN,[273]
356,DECEMBER,26.0,Memoria,Neon,Apichatpong Weerasethakul (director/acreenplay...,NaN,[274]
357,DECEMBER,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if len(result) ==0:
        return np.NaN
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/550?api_key=76d9e7057c5b2a49d4234f80154f044e'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " "
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [167]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [172]:
df_2021 = df[['Title','Cast and crew','genres']]

In [173]:
df_2021

,Title,Cast and crew,genres
0,Shazam!,David F. Sandberg (director); Henry Gayden (sc...,Drama
1,Pet Sematary,"Kevin Kolsch, Dennis Widmyer (directors); Jeff...",Drama
2,The Best of Enemies,Robin Bissell (director/screenplay); Taraji P....,Drama
3,High Life,Claire Denis (director/screenplay); Jean-Pol F...,Drama
4,Unicorn Store,Brie Larson (director); Samantha McIntyre (scr...,Drama
...,...,...,...
188,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Drama
189,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama
190,1917,Sam Mendes (director/screenplay); Krysty Wilso...,Drama
191,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama
192,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [174]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [175]:
df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(str(x)))

<ipython-input-175-059d9cfe3ca6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(str(x)))

In [176]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [177]:
df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(str(x)))

<ipython-input-177-fbf9a4980306>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [178]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [179]:
df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(str(x)))

<ipython-input-179-597eaf6de001>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [180]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [181]:
df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3(str(x)))

<ipython-input-181-e73c3a751ade>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [182]:
df_2021

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Shazam!,David F. Sandberg (director); Henry Gayden (sc...,Drama,David F. Sandberg,Zachary Levi,Asher Angel,Mark Strong
1,Pet Sematary,"Kevin Kolsch, Dennis Widmyer (directors); Jeff...",Drama,"Kevin Kolsch, Dennis Widmyer",Jason Clarke,Amy Seimetz,John Lithgow
2,The Best of Enemies,Robin Bissell (director/screenplay); Taraji P....,Drama,Robin Bissell,Taraji P. Henson,Sam Rockwell,NaN
3,High Life,Claire Denis (director/screenplay); Jean-Pol F...,Drama,Claire Denis,Robert Pattinson,Juliette Binoche,AndrÃ© Benjamin
4,Unicorn Store,Brie Larson (director); Samantha McIntyre (scr...,Drama,Brie Larson,Brie Larson,Samuel L. Jackson,Joan Cusack
...,...,...,...,...,...,...,...
188,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Drama,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones
189,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh
190,1917,Sam Mendes (director/screenplay); Krysty Wilso...,Drama,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong
191,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson
192,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge

In [183]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [184]:
new_df21 = df_2021.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [185]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,David F. Sandberg,Zachary Levi,Asher Angel,Mark Strong,Drama,Shazam!
1,"Kevin Kolsch, Dennis Widmyer",Jason Clarke,Amy Seimetz,John Lithgow,Drama,Pet Sematary
2,Robin Bissell,Taraji P. Henson,Sam Rockwell,NaN,Drama,The Best of Enemies
3,Claire Denis,Robert Pattinson,Juliette Binoche,AndrÃ© Benjamin,Drama,High Life
4,Brie Larson,Brie Larson,Samuel L. Jackson,Joan Cusack,Drama,Unicorn Store
...,...,...,...,...,...,...
188,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Drama,Spies in Disguise
189,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama,Little Women
190,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,Drama,1917
191,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama,Just Mercy
192,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,Clemency

In [186]:
new_df21['actor_2_name'] = new_df21['actor_2_name'].replace(np.nan, 'unknown')
new_df21['actor_3_name'] = new_df21['actor_3_name'].replace(np.nan, 'unknown')

In [187]:
new_df21['movie_title'] = new_df21['movie_title'].str.lower()

In [188]:
new_df21['comb'] = new_df21['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' ' + new_df21['actor_3_name'] + ' ' + new_df21['director_name'] + ' ' + new_df21['genres'] + ' ' + new_df21['movie_title']

In [189]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,David F. Sandberg,Zachary Levi,Asher Angel,Mark Strong,Drama,shazam!,Zachary Levi Asher Angel Mark Strong David F. ...
1,"Kevin Kolsch, Dennis Widmyer",Jason Clarke,Amy Seimetz,John Lithgow,Drama,pet sematary,Jason Clarke Amy Seimetz John Lithgow Kevin Ko...
2,Robin Bissell,Taraji P. Henson,Sam Rockwell,unknown,Drama,the best of enemies,Taraji P. Henson Sam Rockwell unknown Robin Bi...
3,Claire Denis,Robert Pattinson,Juliette Binoche,AndrÃ© Benjamin,Drama,high life,Robert Pattinson Juliette Binoche AndrÃ© Benjam...
4,Brie Larson,Brie Larson,Samuel L. Jackson,Joan Cusack,Drama,unicorn store,Brie Larson Samuel L. Jackson Joan Cusack Brie...
...,...,...,...,...,...,...,...
188,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Drama,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
189,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
190,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,Drama,1917,George MacKay Dean-Charles Chapman Mark Strong...
191,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
192,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

# Extracting features of 2022 movies from wikipedia

In [190]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2022"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [191]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [192]:
df

,Rank,Title,Distributor,Domestic Gross,Opening,Opening.1,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,1.0,The Batman*,Warner Bros.,"$369,309,462",NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Doctor Strange in the Multiverse of Madness*,Disney,"$351,992,340",NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Sonic the Hedgehog 2*,Paramount,"$181,950,102",NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Uncharted,Sony,"$147,726,420",NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,The Lost City*,Paramount,"$99,674,006",NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
175,NaN,"Are You There God? It's Me, Margaret",NaN,NaN,SEPTEMBER,16.0,Lionsgate / Gracie Films,Kelly Fremon Craig (director/screenplay); Rach...,NaN,[144]
176,NaN,Distant,NaN,NaN,SEPTEMBER,16.0,Universal Pictures / DreamWorks Pictures / Amb...,Josh Gordon & Will Speck (directors); Spenser ...,NaN,[145]
177,NaN,Don't Worry Darling,NaN,NaN,SEPTEMBER,23.0,Warner Bros. Pictures / New Line Cinema,Olivia Wilde (director); Katie Silberman (scre...,NaN,[146]
178,NaN,Bros,NaN,NaN,SEPTEMBER,30.0,Universal Pictures / Apatow Productions,Nicholas Stoller (director/screenplay); Billy ...,NaN,[147]
179,NaN,NaN,NaN,NaN,SEPTEMBER,NaN,NaN,NaN,NaN,NaN

In [193]:
! pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\acer\anaconda3\lib\site-packages (1.7.6)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from tmdbv3api) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.10)

In [194]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '76d9e7057c5b2a49d4234f80154f044e'

In [195]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/550?api_key=76d9e7057c5b2a49d4234f80154f044e'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " "
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [196]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [197]:
df_2022 = df[['Title','Cast and crew','genres']]

In [198]:
df_2022

,Title,Cast and crew,genres
0,The Batman*,NaN,Drama
1,Doctor Strange in the Multiverse of Madness*,NaN,Drama
2,Sonic the Hedgehog 2*,NaN,Drama
3,Uncharted,NaN,Drama
4,The Lost City*,NaN,Drama
...,...,...,...
175,"Are You There God? It's Me, Margaret",Kelly Fremon Craig (director/screenplay); Rach...,Drama
176,Distant,Josh Gordon & Will Speck (directors); Spenser ...,Drama
177,Don't Worry Darling,Olivia Wilde (director); Katie Silberman (scre...,Drama
178,Bros,Nicholas Stoller (director/screenplay); Billy ...,Drama
179,NaN,NaN,Drama

In [199]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [200]:
df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(str(x)))

<ipython-input-200-bde37e357dd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(str(x)))

In [201]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [202]:
df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x: get_actor1(str(x)))

<ipython-input-202-e67b31464e65>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [203]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [204]:
df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2(str(x)))

<ipython-input-204-d3d5c35d26fc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [205]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [206]:
df_2022['actor_3_name'] = df_2022['Cast and crew'].map(lambda x: get_actor3(str(x)))

<ipython-input-206-0c65546c30a0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_3_name'] = df_2022['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [207]:
df_2022

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Batman*,NaN,Drama,nan,nan,NaN,NaN
1,Doctor Strange in the Multiverse of Madness*,NaN,Drama,nan,nan,NaN,NaN
2,Sonic the Hedgehog 2*,NaN,Drama,nan,nan,NaN,NaN
3,Uncharted,NaN,Drama,nan,nan,NaN,NaN
4,The Lost City*,NaN,Drama,nan,nan,NaN,NaN
...,...,...,...,...,...,...,...
175,"Are You There God? It's Me, Margaret",Kelly Fremon Craig (director/screenplay); Rach...,Drama,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie
176,Distant,Josh Gordon & Will Speck (directors); Spenser ...,Drama,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto
177,Don't Worry Darling,Olivia Wilde (director); Katie Silberman (scre...,Drama,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde
178,Bros,Nicholas Stoller (director/screenplay); Billy ...,Drama,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Ts Madison
179,NaN,NaN,Drama,nan,nan,NaN,NaN

In [208]:
df_2022 = df_2022.rename(columns={'Title':'movie_title'})

In [215]:
new_df22 = df_2022.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [216]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,nan,nan,NaN,NaN,Drama,The Batman*
1,nan,nan,NaN,NaN,Drama,Doctor Strange in the Multiverse of Madness*
2,nan,nan,NaN,NaN,Drama,Sonic the Hedgehog 2*
3,nan,nan,NaN,NaN,Drama,Uncharted
4,nan,nan,NaN,NaN,Drama,The Lost City*
...,...,...,...,...,...,...
175,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie,Drama,"Are You There God? It's Me, Margaret"
176,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto,Drama,Distant
177,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde,Drama,Don't Worry Darling
178,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Ts Madison,Drama,Bros
179,nan,nan,NaN,NaN,Drama,NaN

In [217]:
new_df22['actor_2_name'] = new_df22['actor_2_name'].replace(np.nan, 'unknown')
new_df22['actor_3_name'] = new_df22['actor_3_name'].replace(np.nan, 'unknown')

In [218]:
new_df22['movie_title'] = new_df22['movie_title'].str.lower()

In [219]:
new_df22['comb'] = new_df22['actor_1_name'] + ' ' + new_df22['actor_2_name'] + ' ' + new_df22['actor_3_name'] + ' ' + new_df22['director_name'] + ' ' + new_df22['genres'] + ' ' + new_df22['movie_title']

In [220]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,nan,nan,unknown,unknown,Drama,the batman*,nan unknown unknown nan Drama the batman*
1,nan,nan,unknown,unknown,Drama,doctor strange in the multiverse of madness*,nan unknown unknown nan Drama doctor strange i...
2,nan,nan,unknown,unknown,Drama,sonic the hedgehog 2*,nan unknown unknown nan Drama sonic the hedgeh...
3,nan,nan,unknown,unknown,Drama,uncharted,nan unknown unknown nan Drama uncharted
4,nan,nan,unknown,unknown,Drama,the lost city*,nan unknown unknown nan Drama the lost city*
...,...,...,...,...,...,...,...
175,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie,Drama,"are you there god? it's me, margaret",Rachel McAdams Abby Ryder Fortson Benny Safdie...
176,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto,Drama,distant,Anthony Ramos Naomi Scott Zachary Quinto Josh ...
177,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde,Drama,don't worry darling,Florence Pugh Harry Styles Olivia Wilde Olivia...
178,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Ts Madison,Drama,bros,Billy Eichner Luke Macfarlane Ts Madison Nicho...
179,nan,nan,unknown,unknown,Drama,NaN,NaN

# Combining data till 2017 and 2018-2022

In [221]:
my_df = new_df18.append(new_df19.append(new_df20.append(new_df21.append(new_df22,ignore_index=True),ignore_index=True),ignore_index=True),ignore_index=True)

In [222]:
my_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Drama,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Drama,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Drama,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Drama,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
1079,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie,Drama,"are you there god? it's me, margaret",Rachel McAdams Abby Ryder Fortson Benny Safdie...
1080,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto,Drama,distant,Anthony Ramos Naomi Scott Zachary Quinto Josh ...
1081,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde,Drama,don't worry darling,Florence Pugh Harry Styles Olivia Wilde Olivia...
1082,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Ts Madison,Drama,bros,Billy Eichner Luke Macfarlane Ts Madison Nicho...
1083,nan,nan,unknown,unknown,Drama,NaN,NaN

In [223]:
old_df = pd.read_csv(r"C:\Users\acer\Downloads\The-Movie-Cinema-master\The-Movie-Cinema-master\datasets\movie.csv")

In [224]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,John Lasseter,Tom Hanks,Tim Allen,Don Rickles,Animation Comedy Family,toy story,Tom Hanks Tim Allen Don Rickles John Lasseter ...
1,Joe Johnston,Robin Williams,Jonathan Hyde,Kirsten Dunst,Adventure Fantasy Family,jumanji,Robin Williams Jonathan Hyde Kirsten Dunst Joe...
2,Howard Deutch,Walter Matthau,Jack Lemmon,Ann-Margret,Romance Comedy,grumpier old men,Walter Matthau Jack Lemmon Ann-Margret Howard ...
3,Forest Whitaker,Whitney Houston,Angela Bassett,Loretta Devine,Comedy Drama Romance,waiting to exhale,Whitney Houston Angela Bassett Loretta Devine ...
4,Charles Shyer,Steve Martin,Diane Keaton,Martin Short,Comedy,father of the bride part ii,Steve Martin Diane Keaton Martin Short Charles...
...,...,...,...,...,...,...,...
36336,Ben Rock,Monty Bane,Lucy Butler,David Grammer,Horror,the burkittsville 7,Monty Bane Lucy Butler David Grammer Ben Rock ...
36337,Aaron Osborne,Lisa Boyle,Kena Land,Zaneta Polard,Sci-Fi,caged heat 3000,Lisa Boyle Kena Land Zaneta Polard Aaron Osbor...
36338,John Irvin,Patrick Bergin,Uma Thurman,David Morrissey,Drama Action Romance,robin hood,Patrick Bergin Uma Thurman David Morrissey Joh...
36339,Lav Diaz,Angel Aquino,Perry Dizon,Hazel Orencio,Drama,century of birthing,Angel Aquino Perry Dizon Hazel Orencio Lav Dia...
36340,Mark L. Lester,Erika Eleniak,Adam Baldwin,Julie du Page,Action Drama Thriller,betrayal,Erika Eleniak Adam Baldwin Julie du Page Mark ...

In [225]:
final_df = old_df.append(my_df,ignore_index=True)

In [226]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,John Lasseter,Tom Hanks,Tim Allen,Don Rickles,Animation Comedy Family,toy story,Tom Hanks Tim Allen Don Rickles John Lasseter ...
1,Joe Johnston,Robin Williams,Jonathan Hyde,Kirsten Dunst,Adventure Fantasy Family,jumanji,Robin Williams Jonathan Hyde Kirsten Dunst Joe...
2,Howard Deutch,Walter Matthau,Jack Lemmon,Ann-Margret,Romance Comedy,grumpier old men,Walter Matthau Jack Lemmon Ann-Margret Howard ...
3,Forest Whitaker,Whitney Houston,Angela Bassett,Loretta Devine,Comedy Drama Romance,waiting to exhale,Whitney Houston Angela Bassett Loretta Devine ...
4,Charles Shyer,Steve Martin,Diane Keaton,Martin Short,Comedy,father of the bride part ii,Steve Martin Diane Keaton Martin Short Charles...
...,...,...,...,...,...,...,...
37420,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie,Drama,"are you there god? it's me, margaret",Rachel McAdams Abby Ryder Fortson Benny Safdie...
37421,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto,Drama,distant,Anthony Ramos Naomi Scott Zachary Quinto Josh ...
37422,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde,Drama,don't worry darling,Florence Pugh Harry Styles Olivia Wilde Olivia...
37423,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Ts Madison,Drama,bros,Billy Eichner Luke Macfarlane Ts Madison Nicho...
37424,nan,nan,unknown,unknown,Drama,NaN,NaN

In [227]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      1
comb             1
dtype: int64

In [228]:
final_df = final_df.dropna(how='any')

In [229]:
final_df.to_csv('final_data.csv',index=False)